spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/meal_voucher
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org.hibernate.engine.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.transaction: DEBUG
